import Head from 'next/head'
import styles from '@/styles/Home.module.css'


export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio-Milkias Tonji</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
         <div className='bg-light min-h-screen w-full flex items-center justify-center flex-col'>
           <h1> Hello there this is the next js project here...</h1>
           <p>What is this again</p>
         </div>
      </main>
    </>
  )
}
