import Image from 'next/image'
import Layout from '../components/Layout'
import Head from 'next/head'

import profilePic from '../../public/images/profile/developer-pic-1.png'

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio-Milkias Tonji</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex flex-col items-center text-dark w-full min-h-screen'>
          <Layout>
              <div className='flex items-center justify-between w-full'>
                  <div className=''><Image src={profilePic} alt='milkiasTonjiPic' /></div>
              </div>
          </Layout>
      </main>
    </>
  )
}
